In [2]:
import mediapipe as mp # Import mediapipe
import cv2 # Import opencv

import csv
import os
import numpy as np
from os import listdir
from glob import glob
from tqdm import tqdm
import tensorflow as tf

# Read Data 
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.pipeline import make_pipeline 
from sklearn.preprocessing import StandardScaler 

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from skimage.transform import resize   # for resizing images
from sklearn.model_selection import train_test_split


from keras.preprocessing import image 
from keras.preprocessing.image  import ImageDataGenerator
from keras.utils import np_utils

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm

from keras.models import load_model
# import vgg16
# from vgg16 import Vgg16
from tensorflow.keras.preprocessing import image
# from keras.applications.vgg16 import VGG16
# from keras.applications.vgg16 import preprocess_input







In [3]:
arr123 = []
fgbg = cv2.createBackgroundSubtractorMOG2()

In [4]:
load_model = load_model("VGG16.h5")

In [5]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
cap = cv2.VideoCapture('video (60).avi')   # capturing the video from the given path
# frameRate = cap.get(1) #frame rate
x=1
count = 0
# removing all other files from the temp folder
files = glob('temp/*')
for f in files:
    os.remove(f)
    
while(cap.isOpened()):
    frameId = cap.get(1) #current frame number
    ret, frame = cap.read()
    if (ret != True):
        break
    if (frameId):
        # storing the frames of this particular video in temp folder
        filename ='temp/' + "_frame%d.jpg" % count;count+=1
        cv2.imwrite(filename, fgbg.apply(frame))
cap.release()

In [31]:
prediction_images = []
images = glob("temp/*.jpg")


for i in range(len(images)):
    img = image.load_img(images[i], target_size=[224,224,3])
    test_image = image.img_to_array(img)
    test_image = test_image/255
    test_image = np.expand_dims(test_image,axis=0)
    tt = load_model.predict(test_image)
    
    print(images[i])
    print(tt)

# val = load_model.predict(np.array(x))



1/1 [==============================] - 0s 279ms/step
temp\_frame0.jpg
[[0.00452277 0.99547726]]
1/1 [==============================] - 0s 51ms/step
temp\_frame1.jpg
[[0.01728815 0.98271185]]
1/1 [==============================] - 0s 56ms/step
temp\_frame10.jpg
[[0.03613157 0.96386844]]
1/1 [==============================] - 0s 53ms/step
temp\_frame100.jpg
[[7.2701665e-04 9.9927300e-01]]
1/1 [==============================] - 0s 41ms/step
temp\_frame101.jpg
[[0.00127667 0.9987233 ]]
1/1 [==============================] - 0s 35ms/step
temp\_frame102.jpg
[[0.00225821 0.9977418 ]]
1/1 [==============================] - 0s 40ms/step
temp\_frame103.jpg
[[1.3626821e-04 9.9986374e-01]]
1/1 [==============================] - 0s 49ms/step
temp\_frame104.jpg
[[4.8659713e-04 9.9951339e-01]]
1/1 [==============================] - 0s 30ms/step
temp\_frame105.jpg
[[3.4429147e-04 9.9965572e-01]]
1/1 [==============================] - 0s 32ms/step
temp\_frame106.jpg
[[5.0598197e-04 9.9949396e-01]]
1/1 

1/1 [==============================] - 0s 35ms/step
temp\_frame244.jpg
[[6.7916227e-04 9.9932086e-01]]
1/1 [==============================] - 0s 32ms/step
temp\_frame245.jpg
[[4.4620238e-04 9.9955374e-01]]
1/1 [==============================] - 0s 33ms/step
temp\_frame246.jpg
[[4.9247243e-04 9.9950755e-01]]
1/1 [==============================] - 0s 33ms/step
temp\_frame247.jpg
[[5.9122214e-04 9.9940884e-01]]
1/1 [==============================] - 0s 36ms/step
temp\_frame248.jpg
[[3.475788e-04 9.996524e-01]]
1/1 [==============================] - 0s 32ms/step
temp\_frame249.jpg
[[3.3850261e-04 9.9966145e-01]]
1/1 [==============================] - 0s 35ms/step
temp\_frame25.jpg
[[0.00925099 0.99074894]]
1/1 [==============================] - 0s 38ms/step
temp\_frame250.jpg
[[1.5010382e-04 9.9984992e-01]]
1/1 [==============================] - 0s 35ms/step
temp\_frame251.jpg
[[3.5465808e-04 9.9964535e-01]]
1/1 [==============================] - 0s 30ms/step
temp\_frame252.jpg
[[1.2358863

ALLLLLLLLLLLLLLLL


In [9]:
# cap = cv2.VideoCapture("video (52).avi")
cap = cv2.VideoCapture("----------------->  video here  <-----------------")


x=1

# removing all other files from the temp folder
files = glob('temp/*')
files2 = glob('temp2/*')

for f in files:
    os.remove(f)
    
for f2 in files2:
    os.remove(f2)
    
while(cap.isOpened()):
    frameId = cap.get(1) #current frame number
    ret, frame = cap.read()
    if (ret != True):
        break
    if (frameId):
        # storing the frames of this particular video in temp folder
        filename ='temp/' + "_frame%d.jpg" % count;count+=1
        cv2.imwrite(filename, fgbg.apply(frame))
        filename2 ='temp2/' + "_frame%d.jpg" % count;count+=1
        cv2.imwrite(filename2, frame)

cap.release()

prediction_images = []
images = glob("temp/*.jpg")
images2 = glob("temp2/*.jpg")



for i in range(len(images)):
    img = image.load_img(images[i], target_size=[224,224,3])
    img2 = cv2.imread(images2[i])

    test_image1 = image.img_to_array(img)
    test_image2 = test_image1/255
    test_image3 = np.expand_dims(test_image2,axis=0)
    tt = load_model.predict(test_image3)

#     print(images[i])
    if tt[0][0] > tt[0][1]:
        print("FALLLLLLLLLL")


    cv2.imshow('original', img2)
    cv2.imshow('MOG', test_image1)


    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 0s 30ms/step


1/1 [==============================] - 0s 28ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 33ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 30ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 27ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 36ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 26ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 26ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 26ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 31ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 33ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 28ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 31ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 28ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 42ms/step
FALLLLLLLLLL
1/1 [==============================] - 0s 40ms/step
FALLLLLLLLLL
1/1 [====================